version: '3'
services:
  db:
    container_name: db_bankline_ms
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: bankline_ms
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_bankline_ms:/var/lib/mysql

volumes:
  db_bankline_ms: